name: Python tests

on:
  push:
    branches: [ main, task2_web_app, task3_auth ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.8.0

    - name: Run tests
      run: |
        pytest